# Generated by Django 4.0.4 on 2022-05-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='country_id',
        ),
    ]
